import { FaGift, FaPersonWalking, FaTree } from "react-icons/fa6";
import {
  GiAlgae,
  GiDragonBalls,
  GiElderberry,
  GiFishingPole,
  GiFlowerPot,
  GiFlute,
  GiHighGrass,
  GiIsland,
  GiMountainCave,
  GiPeriscope,
  GiSpermWhale,
  GiStonePile,
  GiTrade,
} from "react-icons/gi";
import { MdExposurePlus1, MdOutlineTerrain, MdSos } from "react-icons/md";
import { BsWater } from "react-icons/bs";
import { PiBridgeDuotone, PiEggCrackFill } from "react-icons/pi";
import { TbBottleFilled } from "react-icons/tb";

export const methods = {
  walk: <FaPersonWalking />,
  "old-rod": <GiFishingPole />,
  "good-rod": <GiFishingPole />,
  "super-rod": <GiFishingPole />,
  surf: <BsWater />,
  "rock-smash": <GiStonePile />,
  headbutt: <FaTree />,
  "dark-grass": <GiHighGrass />,
  "grass-spots": <GiHighGrass />,
  "cave-spots": <GiMountainCave />,
  "bridge-spots": <PiBridgeDuotone />,
  "super-rod-spots": <GiFishingPole />,
  "surf-spots": <BsWater />,
  "yellow-flowers": <GiFlowerPot />,
  "purple-flowers": <GiFlowerPot />,
  "red-flowers": <GiFlowerPot />,
  "rough-terrain": <MdOutlineTerrain />,
  gift: <FaGift />,
  "gift-egg": <PiEggCrackFill />,
  "only-one": <MdExposurePlus1 />,
  pokeflute: <GiFlute />,
  "headbutt-low": <FaTree />,
  "headbutt-normal": <FaTree />,
  "headbutt-high": <FaTree />,
  "squirt-bottle": <TbBottleFilled />,
  "wailmer-pail": <GiSpermWhale />,
  seaweed: <GiAlgae />,
  "roaming-grass": <GiHighGrass />,
  "roaming-water": <BsWater />,
  "devon-scope": <GiPeriscope />,
  "feebas-tile-fishing": <GiFishingPole />,
  "island-scan": <GiIsland />,
  "sos-encounter": <MdSos />,
  "bubbling-spots": <GiDragonBalls />,
  "berry-piles": <GiElderberry />,
  "npc-trade": <GiTrade />,
  "sos-from-bubbling-spot": <MdSos />,
};
